### ISSUE TITLE
Archive Job hangs in Thunderbird 60

### ISSUE THREAD

**Issue by MrMette** [wangvisual/autoarchive#102]
I upgraded to Thunderbird 60 (32 bit) today and have installed the 0.8 beta Awesome Auto Archive add-on, but it seems that my jobs don't work.

In the beginning it was complaining about not finding/not being able to open the folder, but I don't see those errors any more after reselecting each folder for my jobs (I didn't think about copying the error for that one).

But when I start a job (or if it  starts automatically) it just keeps hanging and doesn't archive anything at all.

I see the following errors in the Error Console:
TypeError: ChromeUtils.generateQI is not a function[Learn More]  autoArchiveService.jsm:384:27

I have also tried to add a new job, but that one doesn't run either.
I have set it up to archive a specific folder for everything that is older than 365 days. No other options are set.

I don't know what else to check. Hopefully this is enough info.
If there is anything I can check, let me know.

Edit:
I forgot to check the closed issues. It seems to be the same issue as: https://github.com/wangvisual/autoarchive/issues/101
I guess the fix will be pushed in the next update of the beta then.

edit 2:
Removed one of the exceptions as it doesn't seem to have anything to do with your add-on

**Comment by wangvisual** [comment]
Please wait for 0.8 official release.

**Comment by waltherm** [comment]
@MrMette this worked for me: https://github.com/wangvisual/autoarchive/issues/104

**Comment by MrMette** [comment]
@waltherm Thanks for letting me know. 

I already patched in the code of https://github.com/wangvisual/autoarchive/issues/101 into my xpi file (by changing the code in the xpi file). It didn't work at first (even after restarting Thunderbird), but it worked after a reboot.

But I obviously rather have an official way to fix it. Thanks again (and thanks for creating the patch to wangvisual). 
This seems to work perfectly fine for me as well.
