### ISSUE TITLE
Subdir Rule(s) not working

### ISSUE THREAD

**Issue by Infinality** [wangvisual/autoarchive#103]
I have TB set up with multiple accounts.  In one of the secondary accounts, I have a rule set to delete everything over 90 days old in a folder, including subfolders.  When I do a run, it doesn't delete anything.  If I specifically go into a subfolder and choose "only" that folder, it works.  So it seems like there is something wrong with the subfolder option.

**Comment by Infinality** [comment]
Oh, also I am using the latest release version 0.8 on Windows 10 x64.

**Comment by abeelen** [comment]
I can also confirm this with 0.8 and TB 60.0 on linux

**Comment by wangvisual** [comment]
It was fixed in my local test, but I can't push to github now as github was blocked by GFW again :-(
