### ISSUE TITLE
TypeError: ChromeUtils.generateQI in 0.8beta

### ISSUE THREAD

**Issue by waltherm** [wangvisual/autoarchive#104]
Trying to dryrun hangs and does not apply any filters. Output of error console attached (masked my personal information).

[2018-09-07_error_log.txt](https://github.com/wangvisual/autoarchive/files/2360145/2018-09-07_error_log.txt)

**Comment by wangvisual** [comment]
Please use https://github.com/wangvisual/autoarchive/blob/master/releases/awsomeAutoArchive-0.8-tb.xpi
