### ISSUE TITLE
No Sub Dir

### ISSUE THREAD

**Issue by matyhaty** [wangvisual/autoarchive#107]
You have fixed this issue, but no release which allows us to use your fix

You fixed it 9 days ago

Could you do a 0.81 release please!

**Comment by wangvisual** [comment]
Please try https://github.com/wangvisual/autoarchive/blob/master/beta/awsomeAutoArchive-0.9-tb.xpi

**Comment by timmaj** [comment]
👍 The beta works perfectly on subdirs again

**Comment by timmaj** [comment]
Correcting: it work**ed** for me. Now I get a "folder already exists" error. When Archie works, Thunderbird tries to recreate folder for some folder, which already habe been achieved earlier. This exception is not caught by Archie.

**Comment by theClassicFreak** [comment]
Loading this XPI on Thunderbird 60.4.0 (32-bit) throws the following error

There was an error during installation: Component returned failure code: 0x8052000b (NS_ERROR_FILE_CORRUPTED) [nsIZipReader.open]
