### ISSUE TITLE
Archiving disabled since 1 month

### ISSUE THREAD

**Issue by ando3k** [wangvisual/autoarchive#109]
Dear all,
Unfortunatley I have the problem that since approximately 1 month the rule that I generated for archiving emails older than 1 year doesn't work any more (before it worked properly). I have not changed anything.
Also manually activating the rule and different trials to disable the add-on and/or the rule did not work.

What might be the reason? Was there an update 1 month ago?
I am running Thunderbird 60.3.2 (32 bit) with Add-on version 0.8 on a Windows 10 computer.

Thanks in advance,
Andreas

**Comment by carlinux** [comment]
I think i have the same issue,
Thunderbird 60. Subfolders aren't evaluated at all but if i move messages to the root folder of the rule it works as intended.
tried an fresh install as well with same results.

**Comment by kokpit** [comment]
> Dear all,
> Unfortunatley I have the problem that since approximately 1 month the rule that I generated for archiving emails older than 1 year doesn't work any more (before it worked properly). I have not changed anything.
> Also manually activating the rule and different trials to disable the add-on and/or the rule did not work.
> 
> What might be the reason? Was there an update 1 month ago?
> I am running Thunderbird 60.3.2 (32 bit) with Add-on version 0.8 on a Windows 10 computer.
> 
> Thanks in advance,
> Andreas

try: https://github.com/wangvisual/autoarchive/blob/master/beta/awsomeAutoArchive-0.9-tb.xpi

**Comment by kokpit** [comment]
> Regards,
> I have been having a similar issue for a while too. (May be the same issue.) I archive messages older than '0' days. It seems that the main folder actually still archives, but the sub-directories doesn't. i.e. I have a folder called General Folders. None of the folders within General Folders archive, however if I move a message to the top level directory folder General Folder, the message is archived. I am running Windows 10 Enterprise, Thunderbird Portable version 60.3.3. I installed a fresh version of Thunderbird portable, installed and re-set up Awesome Auto Archive, and am still having the same issue.

Try: https://github.com/wangvisual/autoarchive/blob/master/beta/awsomeAutoArchive-0.9-tb.xpi

and what are the setings for arhiving is it set to include sudirs...
![untitled](https://user-images.githubusercontent.com/12991536/51116176-a9432400-180a-11e9-93fb-4fd061d43fc4.png)

**Comment by mtiday** [comment]
Yep, it is. The settings hadn't changed for me. One day I noticed it wasn't archiving sub directories any longer.

**Comment by ando3k** [comment]
Thanks, the 0.9beta works!
