### ISSUE TITLE
Donate problem with paypal. Refund demand. Please Answer me !!!!!!!!!!!!!!!!!!!!!!!!!!

### ISSUE THREAD

**Issue by LionelHoudelier** [wangvisual/autoarchive#119]
Hi. I wanted to grant you for this add-on through the donate button with paypal, because it helped me a lot. 
But on the paypal page, the 4.99 $ became 499$ taken on my credit card. I have contacted paypal to explain the problem, and get the refund of the 499$. They have recognized a problem and ask me to contact you first to get refund of the amount. they said also that in case of no refund from you in 5 days, I should contact them again to solve the reclamation process. Sorry for the problem, but I have checked aftewards and there is really a problem on the paypal donate pages...
Hoping to reading you soon.
Best regards,
Lionel Houdelier

**Comment by wangvisual** [comment]
Seems you already got the refund? I have issues with my paypal account, that it was locked, I'm working on that.

So should I change anything? Why 4.99$ becomes 499$?

**Comment by LionelHoudelier** [comment]
Yes. it is all refund. Thanks for the resolve. The bug comes from Firefox ESR on Linux. Could not believe it ! I'll make a new donate. Thanks a lot again for your work.
