### ISSUE TITLE
Too many rules break AAA options window

### ISSUE THREAD

**Issue by vdenisov** [wangvisual/autoarchive#50]
See https://www.dropbox.com/s/cd79z0bhzsc1qzq/aaa.png?dl=0 for a screenshot. Basically, AAA options window should be made resizable; and the list of rules wrapped in a scroll pane.

**Comment by wangvisual** [comment]
Fixed, you can try beta version @ https://github.com/wangvisual/autoarchive/blob/master/beta/awsomeAutoArchive-0.7-tb.xpi

**Comment by vdenisov** [comment]
Thanks a lot, works very well!
