### ISSUE TITLE
TypeError: old is null

### ISSUE THREAD

**Issue by patrikhson** [wangvisual/autoarchive#52]
As displayed here on the image (I have been unable to copy/paste the text) I suddenly after a year o using this get exceptions:

TypeError: old is null at weaveOne/aspect@chrome://awsomeautoarchive/content/app.jsm:63:6

Etc...

This is Thunderbird 31.4.0 on Mac 10.10.1 (14B25), and AwsomeAutoArchive 0.6.

![screen shot 2015-01-23 at 16 48 19](https://cloud.githubusercontent.com/assets/655112/5877448/f39b91f4-a31f-11e4-9fe2-79e8677ad3c9.png)

**Comment by wangvisual** [comment]
Did you always get this error, eg, after restart TB?

**Comment by patrikhson** [comment]
Sorry, did some archiving manually for a while, but am back now.

Yes, I always get this. Even after restart of TB.

**Comment by patrikhson** [comment]
I now use TB 31.5.0 and tried AwsomeAutoArchive 0.7 beta that I just downloaded (Feb 26, 2015).

**Comment by wangvisual** [comment]
Would you please try a clean profile with the latest beta (just uploaded), no other addons, From the code, I don't see any suspect that will cause this strange error.
Thanks.

**Comment by patrikhson** [comment]
That works! I.e. new beta, no other plugins. Hmm...I have here a screen dump that show the plugins I normally have enabled (except the other archive plugin, which is disabled always).
![screen shot 2015-02-27 at 09 17 28](https://cloud.githubusercontent.com/assets/655112/6409287/986a90f2-be61-11e4-8539-4468bbee0755.png)

**Comment by wangvisual** [comment]
Just want to clarify, if you now enable other plugins that normally enabled, the issue still happened?

**Comment by patrikhson** [comment]
No, I can NOT repeat the problem.

I enabled each one of the plugins (except AutoarchiveReloaded) you can see above, and restarted in between.

NO crash.

**Comment by wangvisual** [comment]
OK, then I assume the small changes in latest beta might fix the issue.
Close the issue and please reopen if happens again.

**Comment by patrikhson** [comment]
The problems are back... :-(
![screen shot 2015-03-13 at 15 28 25](https://cloud.githubusercontent.com/assets/655112/6640163/c80a1816-c995-11e4-9c7e-cc32330c24e2.png)

**Comment by wangvisual** [comment]
Would you please try again by only enable this addon and disable others?

**Comment by patrikhson** [comment]
I must say I have swapped to now use MailMate, so I have not been using this archiving tool. Because of this, I can neither confirm, nor deny the problem still exists.

**Comment by LigH-de** [comment]
It still exists in #88 ... and I wonder if this project is still maintained.
