### ISSUE TITLE
Tags filters seem not to work with capital letters

### ISSUE THREAD

**Issue by matthias2t** [wangvisual/autoarchive#53]
All is in the title.
It took me 1 hour to figure out why the tag filter was not working, and it seems it's because I used a capital letter in the filter (although there's one in the tag name).
Is that right ? If yes, it shouldn't take long to correct.

Thank anyway for the work done !

**Comment by wangvisual** [comment]
Fixed, you can try beta @ https://github.com/wangvisual/autoarchive/blob/master/beta/awsomeAutoArchive-0.7-tb.xpi

**Comment by matthias2t** [comment]
Waoh, great !
Very reactive, many thanks !
