### ISSUE TITLE
Question:  Is there a way to pull previous settings from a previous install?

### ISSUE THREAD

**Issue by miridvora** [wangvisual/autoarchive#54]
Hi!

My windowsXP died, so I upgraded to windows7.  However, I was not able to extract settings before the reinstall.

Is there any way to get autoarchive to read its previous config file(s) and do the same thing again?  Or do I have to manually recreate all my rules again?

Thank you!

**Comment by wangvisual** [comment]
If you still have the disks that contains the Thunderbird profile, eg "c:\Users\${foobar}\AppData\Roaming\Thunderbird\Profiles\${something}.default", you can use it as your new profile.

Or you can check if there's one directory under above path named "awsomeautoarchive", the files under in it are backup rules. You can install beta version which have a 'Load' function, or you have to manually change the rules through Thunderbird advanced config.
