### ISSUE TITLE
Enhancement: processing blocks of messages

### ISSUE THREAD

**Issue by lodgmar** [wangvisual/autoarchive#59]
When you choose a number of days for archiving (or something else), and you reach that ammount of days, probably you will be archiving every single days since then, cause there are new messages every day.

It will be great if you can choose TWO numbers of days, the first one (D1) would be the age of messages that have to be considered, and the segond one (D2) would be the age of messages that will be really processed, being D1 >= D2. For example, let's say D1 = 187 and D2 = 180. When messages that are older than half a year and a week are found, "Awesome Auto Archive" will process not only these messages, but also those with an age of a week less. This way, it's sure you won't be archiving messages again in at least a week. I wish I've been able to explain myself ;-)

**Comment by wangvisual** [comment]
Yes, that's the current design. May I ask what's the issue for this? If you think the archive actives too often, there's one advanced settings to let you control 'Start next run after', you can set that to a bit enough number like 7 days. Is that works for you?

Thanks.

**Comment by lodgmar** [comment]
Ooops, I didn't understand that option. I think this is exactly the
behaviour I was suggesting ;-)

Thanks for your fast reply!

________________________
Ignacio Triviño Mosquera

2015-06-08 13:24 GMT+02:00 Opera Wang <notifications@github.com>:
