### ISSUE TITLE
Uncaught exceptions when used with EWS ExQuilla for Exchange on T38

### ISSUE THREAD

**Issue by DobyTang** [wangvisual/autoarchive#60]
Enabled ExQuilla for Exchange and AAA resulting in failure to move messages to local folder and two broad errors being retrieved

Timestamp: 03/07/2015 13:21:08
Error: _mm_FormatDisplayName is not a function
Source File: chrome://mailsummaries/content/folderSummary.js
Line: 1520

and

Timestamp: 03/07/2015 13:22:08
Error: Caught Exception NS_ERROR_NOT_IMPLEMENTED: Component returned failure code: 0x80004001 (NS_ERROR_NOT_IMPLEMENTED) [nsIMsgIncomingServer.verifyLogon]
autoArchiveService.checkServers@chrome://awsomeautoarchive/content/autoArchiveService.jsm:360:21
autoArchiveService._doMoveOrArchiveOne@chrome://awsomeautoarchive/content/autoArchiveService.jsm:905:4
autoArchiveService.doMoveOrArchiveOne/<@chrome://awsomeautoarchive/content/autoArchiveService.jsm:755:13
mailTools.prototype.getMailBody@chrome://exchangecalendar/content/invite-style.js:177:3
mailTools.prototype.fetchMail@chrome://exchangecalendar/content/invite-style.js:234:6
mailTools.prototype.onLoad/this.newMailListener.msgAdded/<@chrome://exchangecalendar/content/invite-style.js:245:33
...
mailTools.prototype.getMailBody@chrome://exchangecalendar/content/invite-style.js:177:3
JS frame :: chrome://awsomeautoarchive/content/autoArchiveService.jsm :: autoArchiveService.checkServers :: line 360

Source File: chrome://awsomeautoarchive/content/autoArchiveService.jsm
Line: 360

**Comment by zdima** [comment]
Is there a chance this crash  @@will be fixed?

Timestamp: 07/07/2016 06:55:45 PM
Error: Caught Exception NS_ERROR_NOT_IMPLEMENTED: Component returned failure code: 0x80004001 (NS_ERROR_NOT_IMPLEMENTED) [nsIMsgIncomingServer.verifyLogon]
autoArchiveService.checkServers@chrome://awsomeautoarchive/content/autoArchiveService.jsm:360:21
autoArchiveService._doMoveOrArchiveOne@chrome://awsomeautoarchive/content/autoArchiveService.jsm:905:4
autoArchiveService.doMoveOrArchiveOne/<@chrome://awsomeautoarchive/content/autoArchiveService.jsm:755:13
JS frame :: chrome://awsomeautoarchive/content/autoArchiveService.jsm :: autoArchiveService.checkServers :: line 360

Source File: chrome://awsomeautoarchive/content/autoArchiveService.jsm
Line: 360

**Comment by will** [comment]
There is no chance that I'll fix it, sorry. I haven't used thunderbird in over a decade :/

**Comment by wangvisual** [comment]
fixed.
