### ISSUE TITLE
[Feature request] Hierarchy scope for archiving

### ISSUE THREAD

**Issue by mikidep** [wangvisual/autoarchive#69]
My office uses Local Folders as a root of all archived mails, keeping hierarchy of subdirectories. The problem is if I select Archive I cannot preserve hierarchy, if I select Move I cannot choose Local Folders as destination root. I think this should be added.

**Comment by wangvisual** [comment]
Archive options is controlled by TB and it do have hierarchy support.

![Uploading Capture-1.jpg…]()

**Comment by wangvisual** [comment]
![capture-1](https://cloud.githubusercontent.com/assets/1171579/10714108/6989a5a2-7b17-11e5-82e4-0759f549c978.jpg)
