### ISSUE TITLE
[Minor Bug] Awesome Autoarchive icon covers status bar updates

### ISSUE THREAD

**Issue by Serret** [wangvisual/autoarchive#7]
I've found a minor issue with the latest version of awesome autoarchive 0.2

When I first installed awesome autoarchive the icon was docked to the right side of the status bar. No issues occured then.

But after rebooting and opening thunderbird again, I noticed the icon was now docked to the left side of the status bar. Because of that, the bar no longer shows any status updates, that is whether I'm receiving or sending emails, etc...

**Comment by wangvisual** [comment]
close too old bug, please open new one if needed.
