### ISSUE TITLE
Thunderbird 51.0b2 hangs on open Options

### ISSUE THREAD

**Issue by RataDP** [wangvisual/autoarchive#78]
I found a bug with this extension.

I have Thunderbird **51.0b2** *(beta edition)* and I just installed **Awesome Auto Archive 0.6**. When I will go to options the Thunderbird hangs and I have to kill it with the taskmanager. Any pop up appear when Options is pressed.

**Expects:**

- OS: Windows 10
- Thunderbird: 51.0b2
- Extension: Awesome Auto Archive 0.6

**Comment by lfxg** [comment]
Same issue with TB 52.1.1.
How can we help  diagnosing  the issue?

Best Regards

**Comment by wangvisual** [comment]
fixed by https://github.com/wangvisual/autoarchive/commit/2db60b0b467fb6061197726ad791190bf6e8d4d2
