### ISSUE TITLE
No "Destination Folder" field in Settings

### ISSUE THREAD

**Issue by francwalter** [wangvisual/autoarchive#81]
Hallo
I used this extension in version 0.6 for a while on my mothers computer but forgot to control if working. Now I see that since long there are no backups (archive function).
In the settings, there is no button or dropdown for the Destination Folder I noticed.
Here a screenshot:
![grafik](https://cloud.githubusercontent.com/assets/927269/23329509/6744794e-fb3a-11e6-9516-e0475001d33a.png)

The Thunderbird version is the 45.7.1 on Windows 7 Prof 64
Is it possible that this good extension doesn't work anymore on actual Thunderbird versions?
I cannot read that here in this ReadMe or else.
Thank

frank

**Comment by wangvisual** [comment]
Archive destination is controlled by TB, Other actions like copy/move can have destination.
