### ISSUE TITLE
thunderbird 52.1.0 (64 bit) auto-archive does not respond

### ISSUE THREAD

**Issue by 150cc** [wangvisual/autoarchive#82]
The icon that appears in the bottom status bar has disappeared. 

Also no longer able to access the preference menu. Please if you can update the add-on to be compatible with the latest version of thunderbird it will be wonderful !!!

**Comment by default50** [comment]
Exact same thing happens to me also on TB 52.1.0 (64 bit) on macOS :(

**Comment by gwi2014** [comment]
I see this in my error console:

```
Caught Exception NS_ERROR_NOT_IMPLEMENTED: Component returned failure code: 0x80004001 (NS_ERROR_NOT_IMPLEMENTED) [nsIMsgIncomingServer.verifyLogon]
autoArchiveService.checkServers@chrome://awsomeautoarchive/content/autoArchiveService.jsm:360:22
autoArchiveService._doMoveOrArchiveOne@chrome://awsomeautoarchive/content/autoArchiveService.jsm:905:5
autoArchiveService.doMoveOrArchiveOne/<@chrome://awsomeautoarchive/content/autoArchiveService.jsm:755:14
mailTools.prototype.getMailBody@chrome://exchangecalendar/content/invite-style.js:179:4
mailTools.prototype.fetchMail@chrome://exchangecalendar/content/invite-style.js:236:7
mailTools.prototype.onLoad/this.newMailListener.msgAdded/<@chrome://exchangecalendar/content/invite-style.js:247:34
JS frame :: chrome://awsomeautoarchive/content/autoArchiveService.jsm :: autoArchiveService.checkServers :: line 360
```

The problem at this point, may be that this is a EWS server added by the [ExQuilla Plugin](https://exquilla.zendesk.com/hc/en-us/articles/212909226-ExQuilla-Overview).

**Comment by hubertmeier** [comment]
the same, no reaction on Linux by pressing the "settings" button, in windows TB hangs while clicking on "settings". I can't use this addon, but there is no alternative, it would be nice if you can fix the problem

**Comment by medisoft** [comment]
The same, but on Mac

**Comment by jpschewe** [comment]
I'm running 52.2.1 and I don't get anything out of the preferences window and no errors in the console.

**Comment by jpschewe** [comment]
I see some forks by @croesch and @jlovision. Does anyone know if these fix the issues?

**Comment by croesch** [comment]
My fork does not address this issue and also I don't face that issue .. sorry :)

**Comment by jpschewe** [comment]
@croesch What version of Thunderbird are you running and on what platform? And are you running the original version or your fork?
Thank you.

**Comment by croesch** [comment]
Sure.

OS: Ubuntu 16.04.2 LTS
TB: 52.2.1
AA: my forked version

**Comment by Rakanishuuuu** [comment]
Hey! Just wanted to say I have the same issue, if I try to go in the options of the extension, Tiby stops responding, I have to kill it.

I have Windows 10, and running Thunderbird 52.2.1 (32 bits).

Thank you!

**Comment by jpschewe** [comment]
OS: Mac 10.11.6
TB: 52.2.1 (64-bit)
AA: 0.8beta from https://github.com/croesch/autoarchive/blob/master/beta/awsomeAutoArchive-0.8beta-tb.xpi

I installed the 0.8 beta version and when I goto the add-ons manager and then click preferences on Awesome Auto Archive nothing happens. There also is not an icon in the tray. I tried uninstalling, restarting Thunderbird and then installing again and I got the same behavior. I also tried a newly created profile and it didn't work either.

When I tried the same version of AA on Ubuntu 16.04.2 with TB 52.2.1 (64-bit), clean install, then I get the status menu button and the options. 

So it seems that there is some difference between the Linux version and the Mac version of Thunderbird that breaks the extension. @croesch any suggestions on what I can do to help debug? I am a software developer, I just haven't spent much time with Thunderbird extensions.

**Comment by croesch** [comment]
@jpschewe sorry me too :smiley: 

Have a look at my TB extension development [_experience_](https://github.com/croesch/autoarchive/commit/854a7a9e2203b627412de7214141dd67bbdbfc0b) :arrow_right: I'm out :wink:

**Comment by bgschaid** [comment]
Same here (52.2.1 64bit on MacOS X)
Is it safe to assume that this project is dead? (no reply by the project owner, open pull requests that are over 2years old)

**Comment by wangvisual** [comment]
alerts.totalOpenTime issue was fixed by https://github.com/wangvisual/autoarchive/commit/0d0247d3531f1a84058d6839ac90270447b833df
