### ISSUE TITLE
AutoArchive not move or archive

### ISSUE THREAD

**Issue by GiorgioGit** [wangvisual/autoarchive#86]
Hi, I have always used aaa but since I installed it (0.7) in a new pc with Thunderbird 52.3.0 (64-bit), it does not move and archive more messages, it tells me "these changes would be applied in real run". I expect that I used a IMAP configuration. Can you help me?

**Comment by wangvisual** [comment]
Please check if you enabled 'dry run' in advanced settings of AAA.
Thanks.

**Comment by GiorgioGit** [comment]
it's enabled

**Comment by wangvisual** [comment]
OK, disable it should work.
Thanks.

**Comment by GiorgioGit** [comment]
thankyou so much! fixed!
